const ADMIN="lorielsilvadosreis014@gmail.com";let minutes=10,mode="leve",circuit=[],idx=0,phase="exercise",left=40,timer=null,sound=true;
const pool={leve:[["Marcha no lugar","🌿"],["Mobilidade de ombros","🔄"],["Agachamento lento","🦵"],["Elevação de joelhos","🚶"],["Prancha adaptada","🧘"],["Alongamento dinâmico","🤸"]],forte:[["Polichinelos","🔥"],["Agachamentos","🦵"],["Flexões adaptadas","💪"],["Mountain climbers","⚡"],["Corrida parada","🏃"],["Prancha","🧱"],["Pular corda imaginária","🪢"]]};
const $=x=>document.getElementById(x);function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function make(){let n=minutes===10?5:minutes===15?7:9,p=shuffle(pool[mode]);circuit=Array.from({length:n},(_,i)=>p[i%p.length]);$("count").textContent=n+" MOVIMENTOS";render();reset()}
function render(){$("exercise-list").innerHTML=circuit.map((x,i)=>`<div class="exercise"><div><b>${String(i+1).padStart(2,"0")} &nbsp;${x[1]} ${x[0]}</b><small>40s exercício • 20s descanso</small></div><strong>40S</strong></div>`).join("");$("round").textContent=`RODADA 0 / ${circuit.length}`}
function fmt(n){return"00:"+String(Math.max(0,n)).padStart(2,"0")}
function ui(){ $("clock").textContent=fmt(left);$("phase").textContent=phase==="exercise"?"EXERCÍCIO":"DESCANSO";$("current").textContent=phase==="exercise"?(circuit[idx]?.[0]||"Pronto"):"Respire e descanse";$("round").textContent=`RODADA ${Math.min(idx+1,circuit.length)} / ${circuit.length}`;let total=phase==="exercise"?40:20;$("progress").style.width=((total-left)/total*100)+"%"}
function beep(f){if(!sound)return;try{let C=AudioContext||webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=f||700;o.connect(g);g.connect(c.destination);g.gain.value=.05;o.start();o.stop(c.currentTime+.13)}catch(e){}}
function reset(){clearInterval(timer);timer=null;idx=0;phase="exercise";left=40;ui()}
function start(){if(!circuit.length)make();if(timer)return;timer=setInterval(()=>{left--;if(left<=0){beep(phase==="exercise"?500:900);if(phase==="exercise"){phase="rest";left=20}else{idx++;if(idx>=circuit.length){clearInterval(timer);timer=null;$("phase").textContent="CONCLUÍDO";$("current").textContent="🔥 Treino finalizado!";$("progress").style.width="100%";beep(1000);return}phase="exercise";left=40}}ui()},1000)}
document.querySelectorAll("[data-time]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-time]").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");minutes=+b.dataset.time;make()});
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-mode]").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");mode=b.dataset.mode;make()});
$("generate").onclick=make;$("shuffle").onclick=make;$("start").onclick=start;$("pause").onclick=()=>{clearInterval(timer);timer=null};$("reset").onclick=reset;$("sound").onclick=()=>{sound=!sound;$("sound").textContent=sound?"🔊":"🔇"};
const modal=$("modal");document.querySelectorAll("[data-login]").forEach(b=>b.onclick=()=>modal.classList.remove("hidden"));$("close").onclick=()=>modal.classList.add("hidden");
$("demo").onclick=()=>{modal.classList.add("hidden");let e=prompt("DEMO — e-mail da conta Google:");if(e){localStorage.setItem("morningfit_user",e);if(e.toLowerCase()===ADMIN.toLowerCase())$("admin").classList.remove("hidden");alert("Login demonstrativo concluído.")}};
$("export").onclick=()=>{let a=document.createElement("a");a.href="data:application/json,"+encodeURIComponent(JSON.stringify({minutes,mode,circuit,admin:ADMIN},null,2));a.download="morningfit-config.json";a.click()};
$("clear").onclick=()=>{localStorage.clear();location.reload()};if((localStorage.getItem("morningfit_user")||"").toLowerCase()===ADMIN.toLowerCase())$("admin").classList.remove("hidden");make();